name: Build
on:
  push:
    branches: [ "test-build" ]   # or "**"
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Build
      run: pyinstaller --onefile --windowed --name mp4analyzer main.py

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: mp4analyzer-${{ runner.os }}
        path: dist/mp4analyzer*

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
    - uses: softprops/action-gh-release@v1
      with:
        files: artifacts/**/*
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
